version: "3.7"

services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4213
      MYSQL_DATABASE: test_db
      MYSQL_USER: zmfl
      MYSQL_PASSWORD: 4213
  
  app:
    depends_on: 
      - db
    image: qwer2
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    ports:
      - "8088:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: test_db
      WORDPRESS_DB_USER: zmfl
      WORDPRESS_DB_PASSWORD: 4213